/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.ProdutoDbc;
import bean.ProdutoVendasDbc;
import dao.ClientesDAO;
import dao.ProdutoDAO;
import java.util.ArrayList;
import java.util.List;
import tools.Util;
import tools.UtilDbc;
import view.JDlgVendas;
import viewControle.ProdutoVendasControle;

/**
 *
 * @author Daniel
 */
public class JDlgVendasProdutos extends javax.swing.JDialog {
    JDlgVendas jDlgVendas;
   public ProdutoVendasControle produtoVendasControle;
    ProdutoDAO produtoDAO;
    /**
     * Creates new form JDlgInclusaoVendas
     */
    public JDlgVendasProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null); 
        produtoVendasControle = new ProdutoVendasControle();
        produtoDAO = new ProdutoDAO();
                
        
        UtilDbc.habilitar(false, jTxtTotalDbc);
        
        ProdutoDAO produtoDAO = new ProdutoDAO();
        List lista = new ArrayList();
        List listaProdutos = produtoDAO.listAll();
        for (int i = 0; i < listaProdutos.size(); i++) {
            jCboProdutoDbc.addItem((ProdutoDbc) listaProdutos.get(i));
        }
        
           
    }
    public ProdutoVendasDbc viewBean() {
        ProdutoVendasDbc produtovendasDbc = new ProdutoVendasDbc();
        int quantidadeDbc = UtilDbc.strInt(jTxtQuantidadeDbc.getText());
        double totalDbc = UtilDbc.strDouble(jTxtTotalDbc.getText());
        produtovendasDbc.setProdutoDbc((ProdutoDbc) jCboProdutoDbc.getSelectedItem());
        
        return produtovendasDbc;
  }
    public void beanView(ProdutoVendasDbc produtoVendasDbc ) {
        String intStr = UtilDbc.intStr(produtoVendasDbc.getQuantidadeDbc());
        String totalDbc = UtilDbc.doubleStr(produtoVendasDbc.getValorUnitarioDbc());
        jCboProdutoDbc.setSelectedItem(produtoVendasDbc.getProdutoDbc());
           
        }
    public void setTelaAnterior(JDlgVendas jDlgVendas) {
        this.jDlgVendas = jDlgVendas;

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCboProdutoDbc = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtQuantidadeDbc = new javax.swing.JTextField();
        jTxtValorUnitarioDbc = new javax.swing.JTextField();
        jTxtTotalDbc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Produto");

        jCboProdutoDbc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCboProdutoDbcItemStateChanged(evt);
            }
        });
        jCboProdutoDbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboProdutoDbcActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantidade");

        jLabel3.setText("Valor Unitario");

        jLabel4.setText("Total");

        jTxtQuantidadeDbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtQuantidadeDbcActionPerformed(evt);
            }
        });
        jTxtQuantidadeDbc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtQuantidadeDbcKeyReleased(evt);
            }
        });

        jTxtValorUnitarioDbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtValorUnitarioDbcActionPerformed(evt);
            }
        });

        jTxtTotalDbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTotalDbcActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Ok .png"))); // NOI18N
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Cancelar .png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCboProdutoDbc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTxtQuantidadeDbc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTxtValorUnitarioDbc, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtTotalDbc)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCboProdutoDbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtQuantidadeDbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtValorUnitarioDbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtTotalDbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCboProdutoDbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboProdutoDbcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboProdutoDbcActionPerformed

    private void jCboProdutoDbcItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCboProdutoDbcItemStateChanged
    if (jCboProdutoDbc.getSelectedIndex() != -1) {
            jTxtQuantidadeDbc.setText("1");
            ProdutoDbc produtoDbc = (ProdutoDbc) jCboProdutoDbc.getSelectedItem();
            jTxtValorUnitarioDbc.setText(UtilDbc.doubleStr(produtoDbc.getPrecoDbc()));
            
        }        
    }//GEN-LAST:event_jCboProdutoDbcItemStateChanged

    private void jTxtValorUnitarioDbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtValorUnitarioDbcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtValorUnitarioDbcActionPerformed

    private void jTxtQuantidadeDbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtQuantidadeDbcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtQuantidadeDbcActionPerformed

    private void jTxtQuantidadeDbcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtQuantidadeDbcKeyReleased
    if (jTxtQuantidadeDbc.getText().isEmpty() == false) {
            double unitario = UtilDbc.strDouble(jTxtValorUnitarioDbc.getText());
            int quantidade = UtilDbc.strInt(jTxtQuantidadeDbc.getText());
            jTxtTotalDbc.setText(String.valueOf(quantidade * unitario));
        } else {
            jTxtTotalDbc.setText("0");
        }       
    }//GEN-LAST:event_jTxtQuantidadeDbcKeyReleased

    private void jTxtTotalDbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTotalDbcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTotalDbcActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        UtilDbc.mensagem("Operacao cancelada");
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ProdutoVendasDbc produtovendasDbc = new ProdutoVendasDbc();
        ProdutoVendasControle vendas = new ProdutoVendasControle();
        produtovendasDbc.setProdutoDbc((ProdutoDbc) jCboProdutoDbc.getSelectedItem());
        produtovendasDbc.setQuantidadeDbc(UtilDbc.strInt(jTxtQuantidadeDbc.getText()));
        produtovendasDbc.setValorUnitarioDbc((int) UtilDbc.strDouble(jTxtValorUnitarioDbc.getText()));
        if (getTitle().toUpperCase().substring(0, 1).equals("I")) {
            
            jDlgVendas.produtoVendasControle.addBean(produtovendasDbc);
        } else {
            jDlgVendas.produtoVendasControle.updateBean(jDlgVendas.getSelectedRowProd(), produtovendasDbc);
        }
        Util.limparCampos(jTxtQuantidadeDbc);
        setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVendasProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVendasProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVendasProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVendasProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVendasProdutos dialog = new JDlgVendasProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<ProdutoDbc> jCboProdutoDbc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTxtQuantidadeDbc;
    private javax.swing.JTextField jTxtTotalDbc;
    private javax.swing.JTextField jTxtValorUnitarioDbc;
    // End of variables declaration//GEN-END:variables
}
