/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.FuncionarioDbc;
import dao.FuncionarioDAO;
import java.text.ParseException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.UtilDbc;
import viewControle.FuncionarioControle;
import viewPesquisa.JDlgFuncionariosNovo;

/**
 *
 * @author Meire
 */
public class JDlgFuncionariosNovoIA extends javax.swing.JDialog {
         private boolean incluindo;
        JDlgFuncionariosNovo jDlgFuncionariosNovo;
        FuncionarioDbc funcionarioDbc;
        FuncionarioDAO funcionarioDAO;
        FuncionarioControle funcionarioControle;
        MaskFormatter maskdata;
        MaskFormatter maskcpf;
        MaskFormatter masktel;
    /**
     * Creates new form JDlgFuncionarios
     */
    public JDlgFuncionariosNovoIA(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        if (incluindo) {
        setTitle("Inclusão de produtos");
        } else {
         setTitle("Alteração de produtos");
        }
        setTitle("Funcionario");
         setLocationRelativeTo(null);
        funcionarioDAO = new FuncionarioDAO();
        try {
            maskcpf = new MaskFormatter("###.###.###-##");
            maskdata = new MaskFormatter("##/##/####");
            masktel = new MaskFormatter("(##)#####-####");
    }catch (ParseException ex) {
            Logger.getLogger(JDlgClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        jFmtCpfDbc.setFormatterFactory(new DefaultFormatterFactory(maskcpf));
        jFmtNumeroTelDbc.setFormatterFactory(new DefaultFormatterFactory(masktel));
           UtilDbc.limparCampos(jFmtCodigoDbc, jFmtCpfDbc, jFmtNumeroTelDbc, jFmtSalarioDbc,jCboDerpDBC, jCboNivelDbc, jTxtEmailDbc, jTxtNomeDbc);
 }
        

    public FuncionarioDbc viewBean() {
        /*SetarId*/
        FuncionarioDbc funcionarioDbc = new FuncionarioDbc();
        int id = UtilDbc.strInt(jFmtCodigoDbc.getText());
        funcionarioDbc.setIdfuncionarioDbc(id);

        /*SetarDoble*/
        double salario = UtilDbc.strDouble(jFmtSalarioDbc.getText());
        funcionarioDbc.setSalarioDbc(salario);
        /*SetarCombo*/
        if (jCboNivelDbc.getSelectedIndex() == 0) {
            funcionarioDbc.setSexoDbc("Masculino");
        } else {
            funcionarioDbc.setSexoDbc("Feminino");
        }
        if (jCboDerpDBC.getSelectedIndex() == 0) {
            funcionarioDbc.setDepartamentoDbc("Vendas");
        } else{
            funcionarioDbc.setDepartamentoDbc("Estoque");     
        }
        /*SetarTexto*/
        funcionarioDbc.setNomeDbc(jTxtNomeDbc.getText());
        funcionarioDbc.setNumeroTelefoneDbc(jFmtNumeroTelDbc.getText());
        funcionarioDbc.setEmailDbc(jTxtEmailDbc.getText());
        funcionarioDbc.setCpfDbc(jFmtCpfDbc.getText()); 
        
       

        return funcionarioDbc;
    }

    public void beanView(FuncionarioDbc funcionarioDbc) {
        /*SetarId*/
        String intStr = UtilDbc.intStr(funcionarioDbc.getIdfuncionarioDbc());
        jFmtCodigoDbc.setText(intStr);
        /*SetarDouble*/

        String salarios = UtilDbc.doubleStr(funcionarioDbc.getSalarioDbc());
        jFmtSalarioDbc.setText(salarios);
        /*SetarTexto*/
        jTxtNomeDbc.setText(funcionarioDbc.getNomeDbc());
        jTxtEmailDbc.setText(funcionarioDbc.getEmailDbc()); 
        jFmtCpfDbc.setText(funcionarioDbc.getCpfDbc());
        jFmtNumeroTelDbc.setText(funcionarioDbc.getNumeroTelefoneDbc());
        String sex = funcionarioDbc.getSexoDbc();
        if(sex.equals("Masculino")){
            jCboNivelDbc.setSelectedIndex(0);
        }else {
            jCboNivelDbc.setSelectedIndex(1);
        }
        String set = funcionarioDbc.getDepartamentoDbc();
        if(set.equals("estoque")){
            jCboDerpDBC.setSelectedIndex(0);
        }else {
           jCboDerpDBC.setSelectedIndex(1);
        }
        
        
    }
   
  
     
       public void setIncluindo(boolean incluindo) {
        this.incluindo = incluindo;
    }
    

     public void setTelaAnterior(JDlgFuncionariosNovo jDlgFuncionariosNovo) {
        this.jDlgFuncionariosNovo = jDlgFuncionariosNovo;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtNomeDbc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtEmailDbc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jFmtSalarioDbc = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCboNivelDbc = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jBtnOk1 = new javax.swing.JButton();
        jBtnCancelar1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jFmtCodigoDbc = new javax.swing.JFormattedTextField();
        jFmtCpfDbc = new javax.swing.JFormattedTextField();
        jFmtNumeroTelDbc = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jCboDerpDBC = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Número de Telefone:");

        jTxtNomeDbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeDbcActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jTxtEmailDbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmailDbcActionPerformed(evt);
            }
        });

        jLabel3.setText("Email:");

        jLabel5.setText("CPF");

        jLabel7.setText("Salário:");

        jLabel9.setText("Departamento:");

        jCboNivelDbc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        jCboNivelDbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboNivelDbcActionPerformed(evt);
            }
        });

        jLabel8.setText("Sexo");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setToolTipText("");
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jBtnOk1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Ok .png"))); // NOI18N
        jBtnOk1.setText("Ok");
        jBtnOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOk1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnOk1);

        jBtnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Cancelar .png"))); // NOI18N
        jBtnCancelar1.setText("Cancelar");
        jBtnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnCancelar1);

        jLabel4.setText("ID");

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel10.setText("Cadastro de Funcionarios");

        jCboDerpDBC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendas", "Estoque" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFmtCodigoDbc, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtNomeDbc, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jCboNivelDbc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 74, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTxtEmailDbc, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtNumeroTelDbc, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jCboDerpDBC, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFmtSalarioDbc, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jFmtCpfDbc)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTxtNomeDbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCboNivelDbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jFmtCodigoDbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(26, 26, 26))
                            .addComponent(jFmtCpfDbc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTxtEmailDbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtNumeroTelDbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtSalarioDbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboDerpDBC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNomeDbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeDbcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeDbcActionPerformed

    private void jTxtEmailDbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmailDbcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEmailDbcActionPerformed

    private void jCboNivelDbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboNivelDbcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboNivelDbcActionPerformed

    private void jBtnOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOk1ActionPerformed
        funcionarioDbc = viewBean();
        funcionarioDAO = new FuncionarioDAO();
        if (incluindo) {
            funcionarioDAO.insert(funcionarioDbc);
            
            List lista = funcionarioDAO.listAll();
            jDlgFuncionariosNovo.funcionarioControle.setList(lista);
            
            UtilDbc.mensagem("Registro incluído com sucesso.");
            
        } else {
            funcionarioDAO.update(funcionarioDbc);
            
            List lista = funcionarioDAO.listAll();
            jDlgFuncionariosNovo.funcionarioControle.setList(lista);
            
            UtilDbc.mensagem("Registro alterado com sucesso.");
        }
        UtilDbc.limparCampos(jFmtCodigoDbc, jFmtCpfDbc,  jFmtNumeroTelDbc, jFmtSalarioDbc, jCboDerpDBC, jCboNivelDbc, jTxtEmailDbc, jTxtNomeDbc);
        this.dispose();
    }//GEN-LAST:event_jBtnOk1ActionPerformed

    private void jBtnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelar1ActionPerformed
       UtilDbc.mensagem("Operação Cancelada!");
       UtilDbc.limparCampos(jFmtCodigoDbc, jFmtCpfDbc,  jFmtNumeroTelDbc, jFmtSalarioDbc, jCboDerpDBC, jCboNivelDbc, jTxtEmailDbc, jTxtNomeDbc);
       this.dispose();
setVisible(false);    }//GEN-LAST:event_jBtnCancelar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgFuncionariosNovoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgFuncionariosNovoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgFuncionariosNovoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgFuncionariosNovoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgFuncionariosNovoIA dialog = new JDlgFuncionariosNovoIA(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar1;
    private javax.swing.JButton jBtnOk1;
    private javax.swing.JComboBox<String> jCboDerpDBC;
    private javax.swing.JComboBox<String> jCboNivelDbc;
    private javax.swing.JFormattedTextField jFmtCodigoDbc;
    private javax.swing.JFormattedTextField jFmtCpfDbc;
    private javax.swing.JFormattedTextField jFmtNumeroTelDbc;
    private javax.swing.JFormattedTextField jFmtSalarioDbc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtEmailDbc;
    private javax.swing.JTextField jTxtNomeDbc;
    // End of variables declaration//GEN-END:variables
}
