/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.UsuariosDbc;
import dao.UsuariosDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.UtilDbc;
import viewPesquisa.JDlgUsuariosPesquisa;
/**
 *
 * @author u03402615100
 */
public class JDlgUsuarios extends javax.swing.JDialog {
    private JDlgUsuariosPesquisa jDlgUsuariosPesquisa;
    private boolean incl;
    MaskFormatter maskcpf;
    MaskFormatter maskdata;
    UtilDbc util;
    
    
    /**
     * Creates new form JDlgUsuarios
     */
    public JDlgUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Usuarios");
        setLocationRelativeTo(null);
        
        UtilDbc.habilitar(false, jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,JTxtCodigo_dbc,jFmtCpf_dbc,jChbAtivo_dbc,JTxtNome_dbc,jFmtData_dbc,JTxtEmail_dbc,JCboSexo_dbc,jPwfSenha_dbc);
        UtilDbc.limparCampos(JTxtCodigo_dbc,jFmtCpf_dbc,jChbAtivo_dbc,JTxtNome_dbc,jFmtData_dbc,JTxtEmail_dbc,JCboSexo_dbc,jPwfSenha_dbc);
        jBtnIncluir.setEnabled(true);
        
       
        try {
            maskcpf = new MaskFormatter("###.###.###-##");
            maskdata = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        jFmtCpf_dbc.setFormatterFactory(new DefaultFormatterFactory(maskcpf));
        jFmtData_dbc.setFormatterFactory(new DefaultFormatterFactory(maskdata));
        
        
        }
     public UsuariosDbc viewBean() {
         /*SetarId*/
        UsuariosDbc usuariosDbc = new UsuariosDbc();
        int id = UtilDbc.strInt(JTxtCodigo_dbc.getText());
        usuariosDbc.setIdusuariosDbc(id);
        /*SetarDatas*/
        Date dataNascimento = UtilDbc.strDate(jFmtData_dbc.getText());
        usuariosDbc.setDataNascDbc(dataNascimento);
        /*SetarTextos*/
        usuariosDbc.setNomeDbc(JTxtNome_dbc.getText());
        usuariosDbc.setEmailDbc(JTxtEmail_dbc.getText());
        usuariosDbc.setCpfDbc(jFmtCpf_dbc.getText());
        usuariosDbc.setSenhaDbc(jPwfSenha_dbc.getText());
        /*SetarCombo*/
        if ((JCboSexo_dbc.getSelectedIndex() == 1)) {
            usuariosDbc.setSexoDbc("Masculino");
        }else {
            usuariosDbc.setSexoDbc("Feminino");
        }
        
        if(jChbAtivo_dbc.isSelected() == true){
        usuariosDbc.setAtivoDbc("S");
        } else {
        usuariosDbc.setAtivoDbc("N");
        }
        return usuariosDbc;

    }

    public void beanView(UsuariosDbc usuariosDbc) {
        /*SetarId*/
        String intStr = UtilDbc.intStr(usuariosDbc.getIdusuariosDbc());
        JTxtCodigo_dbc.setText(intStr);
        /*SetarDatas*/
        String dataNascimento = UtilDbc.dateStr(usuariosDbc.getDataNascDbc());
        jFmtData_dbc.setText(dataNascimento);
        
        JTxtNome_dbc.setText(usuariosDbc.getNomeDbc());
        JTxtEmail_dbc.setText(usuariosDbc.getEmailDbc());
        jFmtCpf_dbc.setText(usuariosDbc.getCpfDbc());
        jPwfSenha_dbc.setText(usuariosDbc.getSenhaDbc());
        
        /*SetarCombos*/
        String sexo = usuariosDbc.getSexoDbc();
        if(sexo.equals("M")){
            JCboSexo_dbc.setSelectedIndex(0);
        }else {
            JCboSexo_dbc.setSelectedIndex(1);
        }
        
        if(usuariosDbc.getAtivoDbc().equals("S") == true){
            jChbAtivo_dbc.setSelected(true);
        } else {
            jChbAtivo_dbc.setSelected(false);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JTxtCodigo_dbc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTxtNome_dbc = new javax.swing.JTextField();
        jFmtData_dbc = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JTxtEmail_dbc = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JCboSexo_dbc = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jPwfSenha_dbc = new javax.swing.JPasswordField();
        jChbAtivo_dbc = new javax.swing.JCheckBox();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jFmtCpf_dbc = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        JTxtCodigo_dbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtCodigo_dbcActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        jLabel6.setText("Data de Nascimento");

        jLabel5.setText("CPF");

        JTxtEmail_dbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtEmail_dbcActionPerformed(evt);
            }
        });

        jLabel7.setText("Email");

        jLabel8.setText("Sexo");

        JCboSexo_dbc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        JCboSexo_dbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCboSexo_dbcActionPerformed(evt);
            }
        });

        jLabel9.setText("Senha");

        jPwfSenha_dbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPwfSenha_dbcActionPerformed(evt);
            }
        });

        jChbAtivo_dbc.setText("Ativo");

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Excluir (1).png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Ok .png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Pesquisa (1).png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Cancelar .png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel10.setText("Cadastro de Usuarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(JTxtCodigo_dbc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jFmtCpf_dbc, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(JTxtNome_dbc)
                    .addComponent(JTxtEmail_dbc, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(JCboSexo_dbc, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jChbAtivo_dbc, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPwfSenha_dbc, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtData_dbc, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(119, 119, 119))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAlterar)
                .addGap(10, 10, 10)
                .addComponent(jBtnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnConfirmar)
                .addGap(14, 14, 14)
                .addComponent(jBtnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnPesquisar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTxtCodigo_dbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtCpf_dbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTxtNome_dbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtData_dbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTxtEmail_dbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPwfSenha_dbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JCboSexo_dbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jChbAtivo_dbc))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnPesquisar)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnConfirmar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTxtCodigo_dbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtCodigo_dbcActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JTxtCodigo_dbcActionPerformed

    private void JTxtEmail_dbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtEmail_dbcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtEmail_dbcActionPerformed

    private void jPwfSenha_dbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPwfSenha_dbcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPwfSenha_dbcActionPerformed

    private void JCboSexo_dbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCboSexo_dbcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCboSexo_dbcActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        UtilDbc.habilitar(true, jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,JTxtCodigo_dbc,jFmtCpf_dbc,jChbAtivo_dbc,JTxtNome_dbc,jFmtData_dbc,JTxtEmail_dbc,JCboSexo_dbc,jPwfSenha_dbc);
        UtilDbc.habilitar(false, jBtnIncluir, jBtnExcluir, jBtnPesquisar, jBtnAlterar);
        UtilDbc.limparCampos(JTxtCodigo_dbc,jFmtCpf_dbc,jChbAtivo_dbc,JTxtNome_dbc,jFmtData_dbc,JTxtEmail_dbc,JCboSexo_dbc,jPwfSenha_dbc);
        incl = true;
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        incl = false;
        UtilDbc.habilitar(true, jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,jFmtCpf_dbc,jChbAtivo_dbc,JTxtNome_dbc,jFmtData_dbc,JTxtEmail_dbc,JCboSexo_dbc,jPwfSenha_dbc);
        UtilDbc.habilitar(false, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar, JTxtCodigo_dbc);
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
    if (UtilDbc.perguntar("Deseja excluir o registro?") == true) {
        UsuariosDbc usuariosDbc = viewBean();
        UsuariosDAO usuariosDAO = new UsuariosDAO();
        usuariosDAO.delete(usuariosDbc);
        UtilDbc.mensagem("Registro Excluido.");
    }else{
        UtilDbc.mensagem("Exclusão Cancelada.");
       }
        UtilDbc.limparCampos(JTxtCodigo_dbc,jFmtCpf_dbc,jChbAtivo_dbc,JTxtNome_dbc,jFmtData_dbc,JTxtEmail_dbc,JCboSexo_dbc,jPwfSenha_dbc);
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
    UsuariosDbc usuarioDbc = viewBean();
    UsuariosDAO usuarioDAO = new UsuariosDAO();
    
    if (incl == true) {
        usuarioDAO.insert(usuarioDbc);
        UtilDbc.mensagem("Registro incluido com sucesso.");
    } else {
        usuarioDAO.update(usuarioDbc);
        UtilDbc.mensagem("Registro alterado com sucesso.");
        }
    
        UtilDbc.habilitar(false, jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,JTxtCodigo_dbc,jFmtCpf_dbc,jChbAtivo_dbc,JTxtNome_dbc,jFmtData_dbc,JTxtEmail_dbc,JCboSexo_dbc,jPwfSenha_dbc);
        UtilDbc.habilitar(true, jBtnIncluir,jBtnPesquisar);
        UtilDbc.limparCampos(JTxtCodigo_dbc,jFmtCpf_dbc,jChbAtivo_dbc,JTxtNome_dbc,jFmtData_dbc,JTxtEmail_dbc,JCboSexo_dbc,jPwfSenha_dbc);
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        jDlgUsuariosPesquisa = new JDlgUsuariosPesquisa(null, true);
        jDlgUsuariosPesquisa.setTitle("Pesquisar");
        jDlgUsuariosPesquisa.setTelaAnterior(this);
        jDlgUsuariosPesquisa.setVisible(true);
        UtilDbc.habilitar(true, jBtnAlterar, jBtnIncluir, jBtnExcluir);
        UtilDbc.habilitar(false, jBtnCancelar, jBtnConfirmar);
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        UtilDbc.mensagem("Operação cancelada!");
        UtilDbc.habilitar(false, jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,JTxtCodigo_dbc,jFmtCpf_dbc,jChbAtivo_dbc,JTxtNome_dbc,jFmtData_dbc,JTxtEmail_dbc,JCboSexo_dbc,jPwfSenha_dbc);
        UtilDbc.habilitar(true, jBtnIncluir, jBtnPesquisar);
        UtilDbc.limparCampos(JTxtCodigo_dbc,jFmtCpf_dbc,jChbAtivo_dbc,JTxtNome_dbc,jFmtData_dbc,JTxtEmail_dbc,JCboSexo_dbc,jPwfSenha_dbc);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgUsuarios dialog = new JDlgUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JCboSexo_dbc;
    private javax.swing.JTextField JTxtCodigo_dbc;
    private javax.swing.JFormattedTextField JTxtEmail_dbc;
    private javax.swing.JTextField JTxtNome_dbc;
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JCheckBox jChbAtivo_dbc;
    private javax.swing.JFormattedTextField jFmtCpf_dbc;
    private javax.swing.JFormattedTextField jFmtData_dbc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPwfSenha_dbc;
    // End of variables declaration//GEN-END:variables
}
