package bean;
// Generated 08/12/2023 10:00:11 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClienteDbc generated by hbm2java
 */
@Entity
@Table(name="cliente_dbc"
    ,catalog="db_daniel_carpes"
)
public class ClienteDbc  implements java.io.Serializable {


     private int idclienteDbc;
     private String nomeDbc;
     private String emailDbc;
     private String telefoneDbc;
     private String estadoCivilDbc;
     private String profissaoDbc;
     private String rgDbc;
     private String cpfDbc;
     private Date dataNascDbc;
     private String enderecoDbc;
     private String estadoDbc;
     private String cidadeDbc;
     private String cepDbc;
     private Date dataRegistroDbc;
     private String formacaoDbc;

    public ClienteDbc() {
    }

	
    public ClienteDbc(int idclienteDbc, String nomeDbc, String emailDbc, String telefoneDbc, String estadoCivilDbc, String profissaoDbc, String rgDbc, String cpfDbc, Date dataNascDbc, String enderecoDbc, String estadoDbc, String cidadeDbc, String cepDbc, Date dataRegistroDbc, String formacaoDbc) {
        this.idclienteDbc = idclienteDbc;
        this.nomeDbc = nomeDbc;
        this.emailDbc = emailDbc;
        this.telefoneDbc = telefoneDbc;
        this.estadoCivilDbc = estadoCivilDbc;
        this.profissaoDbc = profissaoDbc;
        this.rgDbc = rgDbc;
        this.cpfDbc = cpfDbc;
        this.dataNascDbc = dataNascDbc;
        this.enderecoDbc = enderecoDbc;
        this.estadoDbc = estadoDbc;
        this.cidadeDbc = cidadeDbc;
        this.cepDbc = cepDbc;
        this.dataRegistroDbc = dataRegistroDbc;
        this.formacaoDbc = formacaoDbc;
    }
    public ClienteDbc(int idclienteDbc, String nomeDbc, String emailDbc, String telefoneDbc, String estadoCivilDbc, String profissaoDbc, String rgDbc, String cpfDbc, Date dataNascDbc, String enderecoDbc, String estadoDbc, String cidadeDbc, String cepDbc, Date dataRegistroDbc, String formacaoDbc, Set vendasDbcs) {
       this.idclienteDbc = idclienteDbc;
       this.nomeDbc = nomeDbc;
       this.emailDbc = emailDbc;
       this.telefoneDbc = telefoneDbc;
       this.estadoCivilDbc = estadoCivilDbc;
       this.profissaoDbc = profissaoDbc;
       this.rgDbc = rgDbc;
       this.cpfDbc = cpfDbc;
       this.dataNascDbc = dataNascDbc;
       this.enderecoDbc = enderecoDbc;
       this.estadoDbc = estadoDbc;
       this.cidadeDbc = cidadeDbc;
       this.cepDbc = cepDbc;
       this.dataRegistroDbc = dataRegistroDbc;
       this.formacaoDbc = formacaoDbc;
    }
   
     @Id 

    
    @Column(name="idcliente_dbc", unique=true, nullable=false)
    public int getIdclienteDbc() {
        return this.idclienteDbc;
    }
    
    public void setIdclienteDbc(int idclienteDbc) {
        this.idclienteDbc = idclienteDbc;
    }

    
    @Column(name="nome_dbc", nullable=false, length=50)
    public String getNomeDbc() {
        return this.nomeDbc;
    }
    
    public void setNomeDbc(String nomeDbc) {
        this.nomeDbc = nomeDbc;
    }

    
    @Column(name="email_dbc", nullable=false, length=50)
    public String getEmailDbc() {
        return this.emailDbc;
    }
    
    public void setEmailDbc(String emailDbc) {
        this.emailDbc = emailDbc;
    }

    
    @Column(name="telefone_dbc", nullable=false, length=14)
    public String getTelefoneDbc() {
        return this.telefoneDbc;
    }
    
    public void setTelefoneDbc(String telefoneDbc) {
        this.telefoneDbc = telefoneDbc;
    }

    
    @Column(name="estadoCivil_dbc", nullable=false, length=50)
    public String getEstadoCivilDbc() {
        return this.estadoCivilDbc;
    }
    
    public void setEstadoCivilDbc(String estadoCivilDbc) {
        this.estadoCivilDbc = estadoCivilDbc;
    }

    
    @Column(name="profissao_dbc", nullable=false, length=50)
    public String getProfissaoDbc() {
        return this.profissaoDbc;
    }
    
    public void setProfissaoDbc(String profissaoDbc) {
        this.profissaoDbc = profissaoDbc;
    }

    
    @Column(name="rg_dbc", nullable=false, length=9)
    public String getRgDbc() {
        return this.rgDbc;
    }
    
    public void setRgDbc(String rgDbc) {
        this.rgDbc = rgDbc;
    }

    
    @Column(name="cpf_dbc", nullable=false, length=14)
    public String getCpfDbc() {
        return this.cpfDbc;
    }
    
    public void setCpfDbc(String cpfDbc) {
        this.cpfDbc = cpfDbc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNasc_dbc", nullable=false, length=10)
    public Date getDataNascDbc() {
        return this.dataNascDbc;
    }
    
    public void setDataNascDbc(Date dataNascDbc) {
        this.dataNascDbc = dataNascDbc;
    }

    
    @Column(name="endereco_dbc", nullable=false, length=50)
    public String getEnderecoDbc() {
        return this.enderecoDbc;
    }
    
    public void setEnderecoDbc(String enderecoDbc) {
        this.enderecoDbc = enderecoDbc;
    }

    
    @Column(name="estado_dbc", nullable=false, length=50)
    public String getEstadoDbc() {
        return this.estadoDbc;
    }
    
    public void setEstadoDbc(String estadoDbc) {
        this.estadoDbc = estadoDbc;
    }

    
    @Column(name="cidade_dbc", nullable=false, length=50)
    public String getCidadeDbc() {
        return this.cidadeDbc;
    }
    
    public void setCidadeDbc(String cidadeDbc) {
        this.cidadeDbc = cidadeDbc;
    }

    
    @Column(name="cep_dbc", nullable=false, length=50)
    public String getCepDbc() {
        return this.cepDbc;
    }
    
    public void setCepDbc(String cepDbc) {
        this.cepDbc = cepDbc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataRegistro_dbc", nullable=false, length=10)
    public Date getDataRegistroDbc() {
        return this.dataRegistroDbc;
    }
    
    public void setDataRegistroDbc(Date dataRegistroDbc) {
        this.dataRegistroDbc = dataRegistroDbc;
    }

    
    @Column(name="formacao_dbc", nullable=false, length=45)
    public String getFormacaoDbc() {
        return this.formacaoDbc;
    }
    
    public void setFormacaoDbc(String formacaoDbc) {
        this.formacaoDbc = formacaoDbc;
    }

    @Override
    public String toString() {
        return nomeDbc;
    }





}


