package bean;
// Generated 08/12/2023 10:00:11 by Hibernate Tools 4.3.1


import java.lang.Double;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FuncionarioDbc generated by hbm2java
 */
@Entity
@Table(name="funcionario_dbc"
    ,catalog="db_daniel_carpes"
)
public class FuncionarioDbc  implements java.io.Serializable {


     private int idfuncionarioDbc;
     private String nomeDbc;
     private String emailDbc;
     private String numeroTelefoneDbc;
     private String cpfDbc;
     private String sexoDbc;
     private String departamentoDbc;
     private Double salarioDbc;

    public FuncionarioDbc() {
    }

	
    public FuncionarioDbc(int idfuncionarioDbc, String nomeDbc, String emailDbc, String numeroTelefoneDbc, String cpfDbc, String sexoDbc, String departamentoDbc, Double salarioDbc) {
        this.idfuncionarioDbc = idfuncionarioDbc;
        this.nomeDbc = nomeDbc;
        this.emailDbc = emailDbc;
        this.numeroTelefoneDbc = numeroTelefoneDbc;
        this.cpfDbc = cpfDbc;
        this.sexoDbc = sexoDbc;
        this.departamentoDbc = departamentoDbc;
        this.salarioDbc = salarioDbc;
    }
    public FuncionarioDbc(int idfuncionarioDbc, String nomeDbc, String emailDbc, String numeroTelefoneDbc, String cpfDbc, String sexoDbc, String departamentoDbc, Double salarioDbc, Set vendasDbcs) {
       this.idfuncionarioDbc = idfuncionarioDbc;
       this.nomeDbc = nomeDbc;
       this.emailDbc = emailDbc;
       this.numeroTelefoneDbc = numeroTelefoneDbc;
       this.cpfDbc = cpfDbc;
       this.sexoDbc = sexoDbc;
       this.departamentoDbc = departamentoDbc;
       this.salarioDbc = salarioDbc;
    }
   
     @Id 

    
    @Column(name="idfuncionario_dbc", unique=true, nullable=false)
    public int getIdfuncionarioDbc() {
        return this.idfuncionarioDbc;
    }
    
    public void setIdfuncionarioDbc(int idfuncionarioDbc) {
        this.idfuncionarioDbc = idfuncionarioDbc;
    }

    
    @Column(name="nome_dbc", nullable=false, length=50)
    public String getNomeDbc() {
        return this.nomeDbc;
    }
    
    public void setNomeDbc(String nomeDbc) {
        this.nomeDbc = nomeDbc;
    }

    
    @Column(name="email_dbc", nullable=false, length=50)
    public String getEmailDbc() {
        return this.emailDbc;
    }
    
    public void setEmailDbc(String emailDbc) {
        this.emailDbc = emailDbc;
    }

    
    @Column(name="numeroTelefone_dbc", nullable=false, length=14)
    public String getNumeroTelefoneDbc() {
        return this.numeroTelefoneDbc;
    }
    
    public void setNumeroTelefoneDbc(String numeroTelefoneDbc) {
        this.numeroTelefoneDbc = numeroTelefoneDbc;
    }

    
    @Column(name="cpf_dbc", nullable=false, length=15)
    public String getCpfDbc() {
        return this.cpfDbc;
    }
    
    public void setCpfDbc(String cpfDbc) {
        this.cpfDbc = cpfDbc;
    }

    
    @Column(name="sexo_dbc", nullable=false, length=20)
    public String getSexoDbc() {
        return this.sexoDbc;
    }
    
    public void setSexoDbc(String sexoDbc) {
        this.sexoDbc = sexoDbc;
    }

    
    @Column(name="departamento_dbc", nullable=false, length=50)
    public String getDepartamentoDbc() {
        return this.departamentoDbc;
    }
    
    public void setDepartamentoDbc(String departamentoDbc) {
        this.departamentoDbc = departamentoDbc;
    }

    
    @Column(name="salario_dbc", nullable=false, precision=12)
    public Double getSalarioDbc() {
        return this.salarioDbc;
    }
    
    public void setSalarioDbc(Double salarioDbc) {
        this.salarioDbc = salarioDbc;
    }

    @Override
    public String toString() {
        return nomeDbc;
    }





}


