package bean;
// Generated 08/12/2023 10:00:11 by Hibernate Tools 4.3.1


import java.lang.Double;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProdutoDbc generated by hbm2java
 */
@Entity
@Table(name="produto_dbc"
    ,catalog="db_daniel_carpes"
)
public class ProdutoDbc  implements java.io.Serializable {


     private int idprodutoDbc;
     private String nomeDbc;
     private String descricaoDbc;
     private String categoriaDbc;
     private Double precoDbc;
     private int quantidadeDbc;
     private String fornecedorDbc;
     private String serialDbc;

    public ProdutoDbc() {
    }

	
    public ProdutoDbc(int idprodutoDbc, String nomeDbc, String descricaoDbc, String categoriaDbc, Double precoDbc, int quantidadeDbc, String fornecedorDbc, String serialDbc) {
        this.idprodutoDbc = idprodutoDbc;
        this.nomeDbc = nomeDbc;
        this.descricaoDbc = descricaoDbc;
        this.categoriaDbc = categoriaDbc;
        this.precoDbc = precoDbc;
        this.quantidadeDbc = quantidadeDbc;
        this.fornecedorDbc = fornecedorDbc;
        this.serialDbc = serialDbc;
    }
    public ProdutoDbc(int idprodutoDbc, String nomeDbc, String descricaoDbc, String categoriaDbc, Double precoDbc, int quantidadeDbc, String fornecedorDbc, String serialDbc, Set produtoVendasDbcs) {
       this.idprodutoDbc = idprodutoDbc;
       this.nomeDbc = nomeDbc;
       this.descricaoDbc = descricaoDbc;
       this.categoriaDbc = categoriaDbc;
       this.precoDbc = precoDbc;
       this.quantidadeDbc = quantidadeDbc;
       this.fornecedorDbc = fornecedorDbc;
       this.serialDbc = serialDbc;
    }
   
     @Id 

    
    @Column(name="idproduto_dbc", unique=true, nullable=false)
    public int getIdprodutoDbc() {
        return this.idprodutoDbc;
    }
    
    public void setIdprodutoDbc(int idprodutoDbc) {
        this.idprodutoDbc = idprodutoDbc;
    }

    
    @Column(name="nome_dbc", nullable=false, length=60)
    public String getNomeDbc() {
        return this.nomeDbc;
    }
    
    public void setNomeDbc(String nomeDbc) {
        this.nomeDbc = nomeDbc;
    }

    
    @Column(name="descricao_dbc", nullable=false)
    public String getDescricaoDbc() {
        return this.descricaoDbc;
    }
    
    public void setDescricaoDbc(String descricaoDbc) {
        this.descricaoDbc = descricaoDbc;
    }

    
    @Column(name="categoria_dbc", nullable=false, length=20)
    public String getCategoriaDbc() {
        return this.categoriaDbc;
    }
    
    public void setCategoriaDbc(String categoriaDbc) {
        this.categoriaDbc = categoriaDbc;
    }

    
    @Column(name="preco_dbc", nullable=false, precision=12)
    public Double getPrecoDbc() {
        return this.precoDbc;
    }
    
    public void setPrecoDbc(Double precoDbc) {
        this.precoDbc = precoDbc;
    }

    
    @Column(name="quantidade_dbc", nullable=false)
    public int getQuantidadeDbc() {
        return this.quantidadeDbc;
    }
    
    public void setQuantidadeDbc(int quantidadeDbc) {
        this.quantidadeDbc = quantidadeDbc;
    }

    
    @Column(name="fornecedor_dbc", nullable=false)
    public String getFornecedorDbc() {
        return this.fornecedorDbc;
    }
    
    public void setFornecedorDbc(String fornecedorDbc) {
        this.fornecedorDbc = fornecedorDbc;
    }

    
    @Column(name="serial_dbc", nullable=false, length=45)
    public String getSerialDbc() {
        return this.serialDbc;
    }
    
    public void setSerialDbc(String serialDbc) {
        this.serialDbc = serialDbc;
    }

    @Override
    public String toString() {
        return nomeDbc;
    }

   






}


