package bean;
// Generated 08/12/2023 10:00:11 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProdutoVendasDbc generated by hbm2java
 */
@Entity
@Table(name="produto_vendas_dbc"
    ,catalog="db_daniel_carpes"
)
public class ProdutoVendasDbc  implements java.io.Serializable {


     private int idprodutoVendasDbc;
     private ProdutoDbc produtoDbc;
     private VendasDbc vendasDbc;
     private int quantidadeDbc;
     private int valorUnitarioDbc;

    public ProdutoVendasDbc() {
    }

    public ProdutoVendasDbc(int idprodutoVendasDbc, ProdutoDbc produtoDbc, VendasDbc vendasDbc, int quantidadeDbc, int valorUnitarioDbc) {
       this.idprodutoVendasDbc = idprodutoVendasDbc;
       this.produtoDbc = produtoDbc;
       this.vendasDbc = vendasDbc;
       this.quantidadeDbc = quantidadeDbc;
       this.valorUnitarioDbc = valorUnitarioDbc;
    }
   
     @Id 

    
    @Column(name="idproduto_vendas_dbc", unique=true, nullable=false)
    public int getIdprodutoVendasDbc() {
        return this.idprodutoVendasDbc;
    }
    
    public void setIdprodutoVendasDbc(int idprodutoVendasDbc) {
        this.idprodutoVendasDbc = idprodutoVendasDbc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_produto_dbc", nullable=false)
    public ProdutoDbc getProdutoDbc() {
        return this.produtoDbc;
    }
    
    public void setProdutoDbc(ProdutoDbc produtoDbc) {
        this.produtoDbc = produtoDbc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_vendas_dbc", nullable=false)
    public VendasDbc getVendasDbc() {
        return this.vendasDbc;
    }
    
    public void setVendasDbc(VendasDbc vendasDbc) {
        this.vendasDbc = vendasDbc;
    }

    
    @Column(name="quantidade_dbc", nullable=false)
    public int getQuantidadeDbc() {
        return this.quantidadeDbc;
    }
    
    public void setQuantidadeDbc(int quantidadeDbc) {
        this.quantidadeDbc = quantidadeDbc;
    }

    
    @Column(name="valorUnitario_dbc", nullable=false)
    public int getValorUnitarioDbc() {
        return this.valorUnitarioDbc;
    }
    
    public void setValorUnitarioDbc(int valorUnitarioDbc) {
        this.valorUnitarioDbc = valorUnitarioDbc;
    }




}


