package bean;
// Generated 08/12/2023 10:00:11 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsuariosDbc generated by hbm2java
 */
@Entity
@Table(name="usuarios_dbc"
    ,catalog="db_daniel_carpes"
)
public class UsuariosDbc  implements java.io.Serializable {


     private int idusuariosDbc;
     private String nomeDbc;
     private Date dataNascDbc;
     private String emailDbc;
     private String cpfDbc;
     private String sexoDbc;
     private String ativoDbc;
     private String senhaDbc;

    public UsuariosDbc() {
    }

   
    
   
     @Id 

    
    @Column(name="idusuarios_dbc", unique=true, nullable=false)
    public int getIdusuariosDbc() {
        return this.idusuariosDbc;
    }
    
    public void setIdusuariosDbc(int idusuariosDbc) {
        this.idusuariosDbc = idusuariosDbc;
    }

    
    @Column(name="nome_dbc", nullable=false, length=50)
    public String getNomeDbc() {
        return this.nomeDbc;
    }
    
    public void setNomeDbc(String nomeDbc) {
        this.nomeDbc = nomeDbc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNasc_dbc", nullable=false, length=10)
    public Date getDataNascDbc() {
        return this.dataNascDbc;
    }
    
    public void setDataNascDbc(Date dataNascDbc) {
        this.dataNascDbc = dataNascDbc;
    }

    
    @Column(name="email_dbc", nullable=false, length=50)
    public String getEmailDbc() {
        return this.emailDbc;
    }
    
    public void setEmailDbc(String emailDbc) {
        this.emailDbc = emailDbc;
    }

    
    @Column(name="cpf_dbc", nullable=false, length=15)
    public String getCpfDbc() {
        return this.cpfDbc;
    }
    
    public void setCpfDbc(String cpfDbc) {
        this.cpfDbc = cpfDbc;
    }

    
    @Column(name="sexo_dbc", nullable=false, length=20)
    public String getSexoDbc() {
        return this.sexoDbc;
    }
    
    public void setSexoDbc(String sexoDbc) {
        this.sexoDbc = sexoDbc;
    }

    
    @Column(name="ativo_dbc", nullable=false, length=1)
    public String getAtivoDbc() {
        return this.ativoDbc;
    }
    
    public void setAtivoDbc(String ativoDbc) {
        this.ativoDbc = ativoDbc;
    }

    
    @Column(name="senha_dbc", nullable=false, length=20)
    public String getSenhaDbc() {
        return this.senhaDbc;
    }
    
    public void setSenhaDbc(String senhaDbc) {
        this.senhaDbc = senhaDbc;
    }

    @Override
    public String toString() {
        return nomeDbc;
    }




}


