package bean;
// Generated 08/12/2023 10:00:11 by Hibernate Tools 4.3.1


import java.lang.Double;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendasDbc generated by hbm2java
 */
@Entity
@Table(name="vendas_dbc"
    ,catalog="db_daniel_carpes"
)
public class VendasDbc  implements java.io.Serializable {


     private int idvendasDbc;
     private ClienteDbc clienteDbc;
     private FuncionarioDbc funcionarioDbc;
     private Date datadaVendasDbc;
     private Double valorTotalDbc;

    public VendasDbc() {
    }

	
    public VendasDbc(int idvendasDbc, ClienteDbc clienteDbc, FuncionarioDbc funcionarioDbc, Date datadaVendasDbc, Double valorTotalDbc) {
        this.idvendasDbc = idvendasDbc;
        this.clienteDbc = clienteDbc;
        this.funcionarioDbc = funcionarioDbc;
        this.datadaVendasDbc = datadaVendasDbc;
        this.valorTotalDbc = valorTotalDbc;
    }
    public VendasDbc(int idvendasDbc, ClienteDbc clienteDbc, FuncionarioDbc funcionarioDbc, Date datadaVendasDbc, Double valorTotalDbc, Set produtoVendasDbcs) {
       this.idvendasDbc = idvendasDbc;
       this.clienteDbc = clienteDbc;
       this.funcionarioDbc = funcionarioDbc;
       this.datadaVendasDbc = datadaVendasDbc;
       this.valorTotalDbc = valorTotalDbc;
    }
   
     @Id 

    
    @Column(name="idvendas_dbc", unique=true, nullable=false)
    public int getIdvendasDbc() {
        return this.idvendasDbc;
    }
    
    public void setIdvendasDbc(int idvendasDbc) {
        this.idvendasDbc = idvendasDbc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_cliente_dbc", nullable=false)
    public ClienteDbc getClienteDbc() {
        return this.clienteDbc;
    }
    
    public void setClienteDbc(ClienteDbc clienteDbc) {
        this.clienteDbc = clienteDbc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_funcionario_dbc", nullable=false)
    public FuncionarioDbc getFuncionarioDbc() {
        return this.funcionarioDbc;
    }
    
    public void setFuncionarioDbc(FuncionarioDbc funcionarioDbc) {
        this.funcionarioDbc = funcionarioDbc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datadaVendas_dbc", nullable=false, length=10)
    public Date getDatadaVendasDbc() {
        return this.datadaVendasDbc;
    }
    
    public void setDatadaVendasDbc(Date datadaVendasDbc) {
        this.datadaVendasDbc = datadaVendasDbc;
    }

    
    @Column(name="valorTotal_dbc", nullable=false, precision=10)
    public Double getValorTotalDbc() {
        return this.valorTotalDbc;
    }
    
    public void setValorTotalDbc(Double valorTotalDbc) {
        this.valorTotalDbc = valorTotalDbc;
    }



}


